# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  hello-world:
    cmds:
      - tinygo flash --target=arduino -port=/dev/cu.usbserial-3130 ch-1/hello-world/main.go
    silent: true
